# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "uas" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c221fb88-e815-45a0-9733-3c6911939af4";
      fsType = "btrfs";
      options = [ "subvol=root" "ssd" "noatime" "compress=zstd" ];
    };

  boot.initrd.luks.devices."nixcrypt".device = "/dev/disk/by-uuid/812cecb6-1495-4349-8c9f-0cc581cb4ada";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/c221fb88-e815-45a0-9733-3c6911939af4";
      fsType = "btrfs";
      options = [ "subvol=home" "ssd" "noatime" "compress=zstd" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/c221fb88-e815-45a0-9733-3c6911939af4";
      fsType = "btrfs";
      options = [ "subvol=nix" "ssd" "noatime" "compress=zstd" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/c221fb88-e815-45a0-9733-3c6911939af4";
      fsType = "btrfs";
      options = [ "subvol=swap" "ssd" "noatime" "compress=zstd" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7C81-7BDE";
      fsType = "vfat";
    };

  fileSystems."/mnt/secondary" =
    { device = "/dev/sda1";
      fsType = "ext4";
      options = [ "noatime" "nosuid" "nodev" "nofail" "x-gvfs-show" "x-udisks-auth" "x-gvfs-name=Secondary" ];
    };

  swapDevices = [ { device = "/swap/swapfile"; } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp170s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
